//Array with all Majors inserted into Trie by electives.js
//Edit this file if Majors need to be updated

var majors= [
'Accountancy',
'Africana Studies',
'Anthropology',
'Art',
'Asian American Studies',
'Athletic Training',
'Biochemistry',
'Biology',
'Business Administration',
'Central American Studies',
'Chemistry',
'Chicano and Chicana Studies',
'Child and Adolescent Development',
'Cinema and Television Arts',
'Civil Engineering',
'Communication Studies',
'Communicative Disorders',
'Computer Engineering',
'Computer Information Technology',
'Computer Science',
'Construction Management',
'Criminology and Justice Studies',
'Deaf Studies',
'Dietetics and Food Science',
'Economics',
'Electrical Engineering',
'Engineering Management',
'English',
'Environmental and Occupational Health',
'Family and Consumer Sciences',
'Finance',
'Gender and Women’s Studies',
'Geography',
'Geology',
'Health Administration',
'History',
'Hospitality',
'Information Systems',
'Journalism',
'Kinesiology',
'Languages and Cultures',
'Liberal Studies',
'Linguistics',
'Management',
'Manufacturing Systems Engineering',
'Marketing',
'Mathematics',
'Mechanical Engineering',
'Modern Jewish Studies',
'Music',
'Nursing',
'Philosophy',
'Physics',
'Political Science',
'Psychology',
'Public Health',
'Public Sector Management',
'Radiologic Sciences',
'Recreation Management',
'Religious Studies',
'Sociology',
'Spanish',
'Theatre',
'Tourism',
'Urban Studies and Planning'
]


